# Generated by Django 2.0.13 on 2019-08-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postman',
            name='resumo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
