# Generated by Django 2.0.13 on 2019-08-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_produto_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Cidade'),
            preserve_default=False,
        ),
    ]
